const action_type = {
  ADD_OR_EDIT_TODO_REQUEST: 'ADD_OR_EDIT_TODO_REQUEST',
  ADD_OR_EDIT_TODO_SUCCESS: 'ADD_OR_EDIT_TODO_SUCCESS',
  ADD_OR_EDIT_TODO_FAILURE: 'ADD_OR_EDIT_TODO_FAILURE',
  TOGGLE_CHECK: "toggleCheck",
  DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",
  FILTER_TODO: "filterTodo",
  CLEAR_COMPLETED: "clearCompleted",
  TOGGLE_ALL: "toggleAll",
  LOAD_TODO: "loadTodo",
};
export default action_type;
